'use strict';

const fs = require('node:fs');
const path = require('node:path');

const {
  buildFilteredAssetSet,
  loadPluginManifest,
} = require('../../src/cli/plugin');

const REPO_ROOT = path.join(__dirname, '..', '..');
const SKILL_PATH = path.join(REPO_ROOT, 'skills', 'spec-dogfood', 'SKILL.md');
const TEMPLATE_PATH = path.join(
  REPO_ROOT,
  'skills',
  'spec-dogfood',
  'references',
  'dogfood-report-template.md',
);
const TAXONOMY_PATH = path.join(
  REPO_ROOT,
  'skills',
  'spec-dogfood',
  'references',
  'test-matrix-taxonomy.md',
);
const GOVERNANCE_PATH = path.join(
  REPO_ROOT,
  'src',
  'cli',
  'contracts',
  'dual-host-governance',
  'skills-governance.json',
);

function read(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function readJson(filePath) {
  return JSON.parse(read(filePath));
}

describe('spec-dogfood workflow contract', () => {
  test('source skill exposes diff-scoped autonomous dogfood boundaries', () => {
    const skill = read(SKILL_PATH);

    expect(skill).toContain('name: spec-dogfood');
    expect(skill).toContain('## Workflow Contract Summary');
    expect(skill).toContain('diff-scoped');
    expect(skill).toContain('Do not use for collaborative UI polish (`spec-polish`)');
    expect(skill).toContain('ordinary browser smoke tests (`spec-test-browser` when delegated)');
    expect(skill).toContain('broad whole-app exploration');
    expect(skill).toContain('docs/dogfood-reports/<YYYY-MM-DD>-<branch-slug>-dogfood.md');
    expect(skill).toContain('Use `agent-browser` Only For Browser Automation');
    expect(skill).toContain('SPEC_FIRST_BROWSER_HELPER_REQUIRED=1');
    expect(skill).toContain('This does not block spec-first baseline');
    expect(skill).toContain('spec-worktree');
    expect(skill).toContain('spec-debug');
    expect(skill).toContain('spec-commit');
    expect(skill).toContain('spec-compound');
    expect(skill).toContain('Blocked (needs human verify)');
    expect(skill).toContain('Blocked (human decision)');
    expect(skill).toContain('references/dogfood-report-template.md');
    expect(skill).toContain('references/test-matrix-taxonomy.md');
    expect(skill).not.toContain('/ce-dogfood');
    expect(skill).not.toContain('ce-compound');
    expect(skill).not.toContain('/ce-setup');
  });

  test('report template and taxonomy preserve resume and persona evidence shape', () => {
    const template = read(TEMPLATE_PATH);
    const taxonomy = read(TAXONOMY_PATH);

    expect(template).toContain('Generated by `spec-dogfood`');
    expect(template).toContain('| # | Flow | Journey / Scenario | Status | Issue | Fix | Commit |');
    expect(template).toContain('Blocked (needs human verify)');
    expect(template).toContain('Blocked (human decision)');
    expect(template).toContain('Feed substantial ones to `spec-compound`');
    expect(template).not.toContain('/ce-dogfood');
    expect(template).not.toContain('ce-compound');
    expect(taxonomy).toContain('complete user journeys');
    expect(taxonomy).toContain('Persona paper cuts');
    expect(taxonomy).toContain('Mapping files to routes');
  });

  test('dual-host governance and plugin manifest expose dogfood as a public workflow', () => {
    const governance = readJson(GOVERNANCE_PATH);
    const record = governance.skills.find((entry) => entry.skill_name === 'spec-dogfood');
    const manifest = loadPluginManifest();
    const command = manifest.commands.find((entry) => entry.name === 'dogfood');

    expect(record).toMatchObject({
      entry_surface: 'workflow_command',
      command_name: 'dogfood',
      host_delivery: {
        claude: 'command',
        codex: 'skill',
        cursor: 'skill',
        kiro: 'skill',
        qoder: 'command',
      },
    });
    expect(command).toMatchObject({
      filename: 'dogfood.md',
      description: 'Run autonomous diff-scoped browser dogfood QA for a branch or PR',
      argumentHint: '[PR number, branch name, or blank for current branch] [--port PORT]',
      skill: 'spec-dogfood',
    });

    expect(buildFilteredAssetSet('claude').commands.map((entry) => entry.name)).toContain('dogfood');
    expect(buildFilteredAssetSet('codex').commands.map((entry) => entry.name)).not.toContain('dogfood');
    expect(buildFilteredAssetSet('codex').workflowSkills).toContain('spec-dogfood');
    expect(buildFilteredAssetSet('qoder').commands.map((entry) => entry.name)).toContain('dogfood');
  });
});
