'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const ClaudeAdapter = require('../../src/cli/adapters/claude');
const CodexAdapter = require('../../src/cli/adapters/codex');
const { inspectInstalledAssets, syncSkills } = require('../../src/cli/plugin');

const REPO_ROOT = path.join(__dirname, '..', '..');
const SKILL_PATH = path.join(REPO_ROOT, 'skills', 'using-spec-first', 'SKILL.md');
const USING_SPEC_FIRST_EVALS_DIR = path.join(REPO_ROOT, 'skills', 'using-spec-first', 'evals');
const USING_SPEC_FIRST_REFERENCES = [
  'scenario-fingerprint-routing.md',
  'user-next-step-guide-mode.md',
  'multi-session-awareness.md',
  'codex-startup-reminder-boundary.md',
  'routing-red-flags.md',
  'output-risk-profile.md',
  'maintenance-and-fresh-source-eval.md',
  'scope-guards.md',
  'dispatch-boundaries.md',
];
const GOVERNANCE_PATH = path.join(
  REPO_ROOT,
  'src',
  'cli',
  'contracts',
  'dual-host-governance',
  'skills-governance.json',
);
const CLAUDE_SPEC_COMMANDS_DIR = path.join(REPO_ROOT, 'templates', 'claude', 'commands', 'spec');

function read(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function expectContainsAll(content, snippets) {
  for (const snippet of snippets) {
    expect(content).toContain(snippet);
  }
}

function readUsingSpecFirstPackage() {
  return [
    read(SKILL_PATH),
    ...USING_SPEC_FIRST_REFERENCES.map((fileName) => read(path.join(
      REPO_ROOT,
      'skills',
      'using-spec-first',
      'references',
      fileName,
    ))),
  ].join('\n');
}

function markdownSection(content, heading) {
  const marker = `${heading}\n`;
  const start = content.indexOf(marker);
  expect(start).not.toBe(-1);

  const afterHeading = content.slice(start + marker.length);
  const nextHeading = afterHeading.match(/^#{1,3} /m);
  return nextHeading ? afterHeading.slice(0, nextHeading.index) : afterHeading;
}

describe('using-spec-first contracts', () => {
  test('source skill defines the entry-governor contract', () => {
    const skill = readUsingSpecFirstPackage();

    expectContainsAll(skill, [
      'name: using-spec-first',
      'what spec-first workflow or command to run next',
      'standalone meta skill and entry governor',
      'not a command-backed workflow',
      'Contract Summary',
      '| When to use |',
      '| When not to use |',
      'clearly scoped low-risk small edits',
      '| Inputs |',
      '| Outputs |',
      '| Artifacts |',
      '| Failure modes |',
      '| Workflow |',
      '| Downstream consumers |',
      'scripts and CLI commands enforce deterministic invariants when mechanically decidable and prepare deterministic facts',
      'the LLM decides the workflow recommendation above that fact floor',
      'Source Of Truth And Runtime Surface',
      'The managed bootstrap blocks in `CLAUDE.md` and `AGENTS.md` are the using-spec-first minimal entry anchors',
      'generated by `spec-first init` after choosing the target host',
      'substantial-work workflow check',
      'direct-answer allowance',
      'external issue/PR input-surface boundary',
      'small set of common entry anchors',
      'prevent it from becoming a second complete route table',
      'Repair stale or missing runtime guidance with `spec-first init` after choosing the target host',
      'If You Are Already In A Workflow',
      'If You Are A Subagent',
      'Lightweight Direct Outcomes',
      'current-context or current-instruction explanations',
      'current conversation or a user-provided single document',
      'they do not require brainstorm, plan, work, review, Graphify, or durable artifacts by default',
      'clearly scoped, single-point, low-risk code/prose/config edits',
      'Clearly scoped small edits may also proceed as normal execution without opening a public workflow',
      'update `CHANGELOG.md` when project policy requires it',
      'use the narrowest meaningful verification',
      'respect source/runtime boundaries',
      'reclassify it at that point and route normally',
      'Decision Output Contract',
      'If the user names a standalone skill, use that skill only when its own scope fits',
      'do not convert it into public workflow admission',
      'Skill Trigger vs Workflow Admission',
      'A skill trigger is source/methodology loading; it is not automatically public workflow admission',
      'Public workflow admission happens only when the current intent actually matches a public `spec-*` workflow',
      'does not grant host-level subagent dispatch beyond the dispatch rules below',
      'User Next-Step Guide Mode',
      'when the user explicitly asks what to run next',
      'which `spec-first` command to use',
      'This mode is read-only.',
      'must not create brainstorm, plan, task, review, solution, or runtime artifacts',
      'Output exactly one best next entrypoint, one concrete reason, and one next action',
      'Do not print the full workflow menu.',
      '推荐入口: <current-host entrypoint>',
      '理由: <one concrete reason>',
      '下一步: <one action the user can take now>',
      'active `CLAUDE.md` / `AGENTS.md` `spec-first:lang` block sets English',
      'Recommended entrypoint',
      'reply `continue` to run it now',
      'Use the Routing Priority and Routing Rules in `skills/using-spec-first/SKILL.md` as the source of truth',
      'Use the exact current-host public entrypoint those rules select',
      'Low-confidence cases need one narrow confirmation before routing',
      'a change could be either a bug fix or a product behavior change',
      'If a brainstorm requirements document exists and implementation direction is not yet planned, recommend plan.',
      'If there is an existing diff and the user asks whether it is ready, recommend code review or doc review based on the artifact.',
      'After init, prefer setup/readiness guidance only when the user asks about setup/readiness',
      'After init, when runtime or MCP readiness is unresolved but the user has a clear lightweight docs, small-code, plan, work, or review goal',
      'route by that goal and require the selected workflow to disclose degraded setup/MCP evidence when relevant',
      'Spec-First Self-Work',
      'docs/10-prompt/结构化项目角色契约.md',
      'host instruction blocks',
      'Clearly scoped, single-point, low-risk ordinary code/prose corrections in `spec-first` itself may proceed directly',
      'Route substantial concrete implementation or prose changes to:',
      'Route review-only requests by artifact type: code/diff/PR quality review to `spec-code-review`, requirements/plan/Markdown review to `spec-doc-review`, and skill/agent asset governance audits to `spec-skill-audit`.',
      'If the request asks for review plus concrete revisions, route to work and keep a review posture during execution.',
      'For source changes, update source-of-truth files, the narrowest contract tests, and `CHANGELOG.md`',
      'Do not modify generated `.claude/`, `.codex/`, or `.agents/skills/` mirrors',
      'Parent Workspace Direct Reads',
      'If the user asks a read-only codebase question from a parent workspace containing multiple child Git repos',
      'Use bounded direct reads in the likely child repo candidates and state the target-repo assumption.',
      'explicit `target_repo` / per-child scope',
      'Explicit Route Normalization',
      "If the user names the other host's equivalent public workflow, translate it to the current host entrypoint",
      '/spec:work`, `$spec-work`, and `spec-work` all refer to `spec-work`',
      'Do not invent a `spec-*` command for standalone skills',
      'Workflow Dispatch Admission',
      'Routing into a public workflow authorizes that workflow to run.',
      'It does not by itself override host-level subagent tool contracts.',
      'call `spawn_agent` only when the current request explicitly asks for subagents, delegated work, parallel agents, persona reviewer dispatch',
      'or when an upstream workflow delegates from an already authorized multi-agent context whose visible parent request or handoff evidence includes explicit subagent/delegation/parallel/persona wording',
      'Some public workflows prefer multi-persona or research phases when host capability and authorization are both present',
      'spec-doc-review` multi-persona document reviewers',
      'record `dispatch_authorization_missing` and make the opt-in path user-visible',
      'for multi-persona or subagent review, ask for `subagents`, `personas`, delegated review, or parallel agents in the request',
      'If the user names `spec-doc-review` in a document-review request without the `$` prefix',
      'normalize it to the current host\'s public document-review entrypoint',
      'Do not invent extra dispatch authorization from normalization',
      'explicit dispatch authorization is absent',
      'follow that workflow\'s documented fallback instead of dispatching',
      'Routing Priority',
      'Optimization routes',
      'Routing Red Flags',
      'Direct editing is fine for clearly scoped, low-risk small edits',
      'runtime delivery, multi-file behavior, or sensitive surfaces',
      'Do not chain multiple workflows automatically',
      'Do not route by keyword alone',
      'It does **not** exist to force every task through brainstorming.',
      'Do **not** make `spec-brainstorm` the universal default front door.',
      'Do **not** adopt the `using-superpowers` rule',
      'Do **not** restore `/spec:*` or `$spec-*` as current product surfaces',
      'Do **not** create host-specific public workflow names when the unified `spec-*` id already exists.',
      'Public workflow identifiers use the unified `spec-*` form across hosts.',
      'Claude and Qoder project commands are generated as `spec-*.md` command files.',
      'Codex, Cursor, and Kiro expose the same names as generated Skills where supported by the host.',
      'spec-doc-review` means the document-review workflow. It uses bounded reviewer dispatch only when the current request also satisfies Codex `spawn_agent` authorization',
      'Codex Startup Reminder Boundary',
      'not a verified deterministic SessionStart hook',
      'top-level Codex orchestrator',
      'spec-first startup-reminder --codex',
      'Missing CLI, command failure, network failure, empty output, or malformed local state must be ignored',
      'Version reminders point to running `spec-first update` in the terminal',
      'Bounded subagents, leaf reviewers, and worker agents must not run the startup reminder',
      'They inherit the parent task scope.',
      'do not reload or invoke `using-spec-first` just to bootstrap yourself',
      '`using-spec-first` governs **entry routing only**',
      'Artifact And Evidence Boundaries',
      'This skill should not ask the agent to fabricate command results',
      'Do not use this governor to create pseudo-plan, pseudo-task, or pseudo-review artifacts.',
      'Do **not** expose internal-only skills as user entrypoints.',
      '`git-worktree`',
      'using-spec-first` itself is a standalone meta skill',
      'spec-doc-review',
      'spec-skill-audit',
      'spec-app-consistency-audit',
      'spec-prd',
      'brownfield PRD authoring',
      'spec-optimize',
      'spec-plan',
      'spec-write-tasks',
      'public optional derived workflow between plan and work',
      'spec-work',
      'Ordinary execution-ready work routes to the stable work entrypoint.',
      'skills/using-spec-first/evals/routing-cases.json',
      'skills/using-spec-first/evals/routing-discipline-cases.json',
      'skills/using-spec-first/references/scenario-fingerprint-routing.md',
      'skills/using-spec-first/references/user-next-step-guide-mode.md',
      'skills/using-spec-first/references/multi-session-awareness.md',
      'skills/using-spec-first/references/codex-startup-reminder-boundary.md',
      'skills/using-spec-first/references/routing-red-flags.md',
      'skills/using-spec-first/references/output-risk-profile.md',
      'skills/using-spec-first/references/maintenance-and-fresh-source-eval.md',
      'not a deterministic router',
    ]);

    expect(skill).not.toContain('/spec:standards');
    expect(skill).not.toContain('$spec-standards');
    expect(skill).not.toContain('/spec:setup');
    expect(skill).not.toContain('$spec-setup');
    expect(skill).not.toContain('generated by `spec-first init --codex` or `spec-first init --codex`');
    expect(skill).not.toContain('with `spec-first init --codex` or `spec-first init --codex`');
    expect(skill).not.toContain('spec-session-inventory');
    expect(skill).not.toContain('spec-session-extract');
    expect(skill).not.toContain('/spec:pr-description');
    expect(skill).not.toContain('$spec-pr-description');
    expect(skill).not.toContain('/spec:next');
    expect(skill).not.toContain('$spec-next');
    expect(skill).not.toContain('/spec:guide');
    expect(skill).not.toContain('$spec-guide');
  });

  test('source route map does not expose the retired spec-intake entrypoint', () => {
    const routeMap = markdownSection(read(SKILL_PATH), '### Route Map');
    const sourcePackage = readUsingSpecFirstPackage();
    const evalFixtures = fs.readdirSync(USING_SPEC_FIRST_EVALS_DIR)
      .filter((fileName) => fileName.endsWith('.json'))
      .sort()
      .map((fileName) => read(path.join(USING_SPEC_FIRST_EVALS_DIR, fileName)))
      .join('\n');
    const governance = read(GOVERNANCE_PATH);
    const commandTemplateNames = fs.readdirSync(CLAUDE_SPEC_COMMANDS_DIR)
      .filter((fileName) => fileName.endsWith('.md'));
    const checkedSurfaces = {
      routeMap,
      sourcePackage,
      evalFixtures,
      governance,
      commandTemplateNames: commandTemplateNames.join('\n'),
    };
    const retiredTokens = [
      'spec-intake',
      '/spec:intake',
      '$spec-intake',
      'intake-brief',
      'intake-notes',
      'ready-for-agent',
    ];

    for (const content of Object.values(checkedSurfaces)) {
      for (const token of retiredTokens) {
        expect(content).not.toContain(token);
      }
    }
    expect(commandTemplateNames).not.toContain('intake.md');
  });

  test('using-spec-first references are source package assets, not decorative files', () => {
    const skill = read(SKILL_PATH);

    for (const fileName of USING_SPEC_FIRST_REFERENCES) {
      const relativePath = `skills/using-spec-first/references/${fileName}`;
      const absolutePath = path.join(REPO_ROOT, relativePath);

      expect(fs.existsSync(absolutePath)).toBe(true);
      expect(skill).toContain(relativePath);
    }
  });

  test('skills governance exposes using-spec-first as a standalone meta skill on both hosts', () => {
    const governance = JSON.parse(read(GOVERNANCE_PATH));

    expect(governance.skills).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          skill_name: 'using-spec-first',
          entry_surface: 'standalone_skill',
          command_name: null,
          host_scope: 'dual_host',
          owner_host: null,
          host_delivery: {
            claude: 'skill',
            codex: 'skill',
            kiro: 'skill',
            qoder: 'skill',
          },
        }),
      ]),
    );
  });

  test('runtime transforms preserve internal guidance text when transformed directly', () => {
    const sourceSkill = read(SKILL_PATH);
    const sourcePackage = readUsingSpecFirstPackage();
    const claude = new ClaudeAdapter();
    const codex = new CodexAdapter();
    const claudeRuntime = claude.transformSkillContent(sourceSkill);
    const codexRuntime = codex.transformSkillContent(sourceSkill, { skillName: 'using-spec-first' });

    expect(claudeRuntime).toContain('name: using-spec-first');
    expect(codexRuntime).toContain('name: using-spec-first');
    expect(claudeRuntime).toContain('Public workflow identifiers use the unified `spec-*` form across hosts.');
    expect(codexRuntime).toContain('Public workflow identifiers use the unified `spec-*` form across hosts.');
    expect(codexRuntime).toContain('spec-first startup-reminder --codex');
    expect(codexRuntime).not.toContain('query proof after setup');
    expect(codexRuntime).toContain('Workflow Dispatch Admission');
    expect(codexRuntime).toContain('It does not by itself override host-level subagent tool contracts.');
    expect(codexRuntime).toContain('call `spawn_agent` only when the current request explicitly asks for subagents, delegated work, parallel agents, persona reviewer dispatch');
    expect(codexRuntime).toContain('visible parent request or handoff evidence includes explicit subagent/delegation/parallel/persona wording');
    expect(codexRuntime).toContain('record `dispatch_authorization_missing` and make the opt-in path user-visible');
    expect(codexRuntime).toContain('for multi-persona or subagent review, ask for `subagents`, `personas`, delegated review, or parallel agents in the request');
    expect(codexRuntime).toContain('spec-doc-review` means the document-review workflow. It uses bounded reviewer dispatch only when the current request also satisfies Codex `spawn_agent` authorization');
    expect(codexRuntime).toContain('generated by `spec-first init` after choosing the target host');
    expect(codexRuntime).toContain('Repair stale or missing runtime guidance with `spec-first init` after choosing the target host');
    expect(codexRuntime).toContain('minimal entry anchors');
    expect(codexRuntime).toContain('Skill Trigger vs Workflow Admission');
    expect(codexRuntime).toContain('A skill trigger is source/methodology loading; it is not automatically public workflow admission');
    expect(codexRuntime).not.toContain('generated by `spec-first init --codex` or `spec-first init --codex`');
    expect(codexRuntime).not.toContain('with `spec-first init --codex` or `spec-first init --codex`');
    expect(codexRuntime).toContain('Bounded subagents, leaf reviewers, and worker agents must not run the startup reminder');
    expect(codexRuntime).toContain('using-spec-first` itself is a standalone meta skill');
    expect(claudeRuntime).toContain('User Next-Step Guide Mode');
    expect(codexRuntime).toContain('User Next-Step Guide Mode');
    expect(claudeRuntime).toContain('Output exactly one best next entrypoint, one concrete reason, and one next action');
    expect(claudeRuntime).toContain('推荐入口: <current-host entrypoint>');
    expect(codexRuntime).toContain('Next action');
    expect(codexRuntime).toContain('This mode is read-only.');
    expect(sourcePackage).toContain('Version reminders point to running `spec-first update` in the terminal');
    expect(sourcePackage).toContain('Low-confidence cases need one narrow confirmation before routing');
    expect(sourcePackage).toContain('Direct editing is fine for clearly scoped, low-risk small edits');
    expect(claudeRuntime).toContain('Claude Code installs it as `.claude/skills/using-spec-first/SKILL.md`');
    expect(claudeRuntime).toContain('Codex installs it as `.agents/skills/using-spec-first/SKILL.md`');
    expect(codexRuntime).toContain('Claude Code installs it as `.claude/skills/using-spec-first/SKILL.md`');
    expect(codexRuntime).toContain('Codex installs it as `.agents/skills/using-spec-first/SKILL.md`');
  });

  test('runtime install notes do not rewrite using-spec-first source-of-truth path', () => {
    const projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'using-spec-first-codex-runtime-'));

    try {
      for (const [adapter, runtimePath] of [
        [new ClaudeAdapter(), path.join(projectRoot, '.claude', 'skills', 'using-spec-first', 'SKILL.md')],
        [new CodexAdapter(), path.join(projectRoot, '.agents', 'skills', 'using-spec-first', 'SKILL.md')],
      ]) {
        syncSkills(projectRoot, adapter);
        const status = inspectInstalledAssets(projectRoot, adapter).skills;
        const usingSpecFirstDrift = status.drifted.find((entry) => entry.skillName === 'using-spec-first');
        const runtime = read(runtimePath);

        expect(usingSpecFirstDrift).toBeUndefined();
        expect(runtime).toContain('Claude Code installs it as `.claude/skills/using-spec-first/SKILL.md`');
        expect(runtime).toContain('Codex installs it as `.agents/skills/using-spec-first/SKILL.md`');
        expect(runtime).toContain('`skills/using-spec-first/SKILL.md` is the source-of-truth routing policy.');
        expect(runtime).not.toContain('`.claude/skills/using-spec-first/SKILL.md` is the source-of-truth routing policy.');
        expect(runtime).not.toContain('`.agents/skills/using-spec-first/SKILL.md` is the source-of-truth routing policy.');
      }
    } finally {
      fs.rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  test('Codex adapter preserves dual-host init guidance while rewriting source runtime paths', () => {
    const codex = new CodexAdapter();
    const rendered = codex.transformSkillContent(
      [
        'Repair with spec-first init and choose the target host.',
        'See `.claude/commands/spec-work.md` for the command path.',
      ].join('\n'),
      {
        skillName: 'using-spec-first',
        isWorkflowSkill: true,
      },
    );

    expect(rendered).toContain('spec-first init and choose the target host');
    expect(rendered).not.toContain('spec-first init --codex or spec-first init --codex');
    expect(rendered).toContain('`.agents/skills/spec-work/SKILL.md`');
  });

  // P1-8 防回归:internal_only skill 的 SKILL.md 不得自称一级入口。它们由公开
  // workflow 委托或用户在已知上下文中直接唤起,但不是 routable 菜单项,文案不应
  // 与 using-spec-first 入口治理(internal helper 非用户入口)对抗。
  test('internal_only skills do not self-declare as first-class entrypoints', () => {
    const governance = JSON.parse(read(GOVERNANCE_PATH));
    const internalSkills = governance.skills
      .filter((skill) => skill.entry_surface === 'internal_only')
      .map((skill) => skill.skill_name);

    const offenders = [];
    for (const skillName of internalSkills) {
      const skillPath = path.join(REPO_ROOT, 'skills', skillName, 'SKILL.md');
      if (!fs.existsSync(skillPath)) continue;
      const content = read(skillPath);
      if (/first-class entry point/i.test(content) || /do not require an upstream caller/i.test(content)) {
        offenders.push(skillName);
      }
    }

    expect(offenders).toEqual([]);
  });

  // R1 drift-detection:被下沉到 references 的关键 Hard Rule / scope-guard / dispatch
  // 断言串必须实际存在于对应 reference 文件,防 reference 被清空后并集 containsAll
  // 靠 SKILL 残留静默通过(SKILL 主面只留概述指针,不应逐字重复完整断言串)。
  test('sunk assertion strings live in their registered reference, not just the SKILL union', () => {
    const routingRedFlags = read(path.join(
      REPO_ROOT, 'skills', 'using-spec-first', 'references', 'routing-red-flags.md',
    ));
    const scopeGuards = read(path.join(
      REPO_ROOT, 'skills', 'using-spec-first', 'references', 'scope-guards.md',
    ));
    const dispatchBoundaries = read(path.join(
      REPO_ROOT, 'skills', 'using-spec-first', 'references', 'dispatch-boundaries.md',
    ));

    // Hard Rules 完整断言串必须在 routing-red-flags.md(SKILL 主面仅留概述指针)
    expect(routingRedFlags).toContain('Do **not** make `spec-brainstorm` the universal default front door.');
    expect(routingRedFlags).toContain('Do **not** adopt the `using-superpowers` rule');
    expect(routingRedFlags).toContain('Do **not** restore `/spec:*` or `$spec-*` as current product surfaces');
    expect(routingRedFlags).toContain('Do **not** create host-specific public workflow names when the unified `spec-*` id already exists.');
    expect(routingRedFlags).toContain('Do **not** expose internal-only skills as user entrypoints.');
    expect(routingRedFlags).toContain('`git-worktree`');

    // Scope Guards 详细规则必须在 scope-guards.md(SKILL 主面仅留指针)
    expect(scopeGuards).toContain('If You Are Already In A Workflow');
    expect(scopeGuards).toContain('Lightweight Direct Outcomes');
    expect(scopeGuards).toContain('reclassify it at that point and route normally');
    expect(scopeGuards).toContain('Parent Workspace Direct Reads');
    expect(scopeGuards).toContain('A skill trigger is source/methodology loading');

    // Dispatch 详细 elaboration 必须在 dispatch-boundaries.md
    expect(dispatchBoundaries).toContain('record `dispatch_authorization_missing` and make the opt-in path user-visible');
    expect(dispatchBoundaries).toContain('spec-doc-review` means the document-review workflow');
  });

  // R-05: 红旗不得含反转 skill 名 bug-report，真实名是 report-bug
  test('routing red flags use the real report-bug skill name, not the reversed bug-report', () => {
    const routingRedFlags = read(path.join(
      REPO_ROOT, 'skills', 'using-spec-first', 'references', 'routing-red-flags.md',
    ));

    expect(routingRedFlags).toContain('report-bug helpers');
    expect(routingRedFlags).not.toContain('bug-report');
  });

  // R-07: 红旗 route target 不得用裸名 update/setup，应指向明确入口
  test('routing red flags route target uses explicit setup entrypoints, not bare names', () => {
    const routingRedFlags = read(path.join(
      REPO_ROOT, 'skills', 'using-spec-first', 'references', 'routing-red-flags.md',
    ));

    expect(routingRedFlags).toContain('`spec-first update`');
    expect(routingRedFlags).toContain('`spec-mcp-setup`');
    expect(routingRedFlags).not.toContain('Route to `update` or `setup` first');
  });

  // R-06: sensitive surfaces 必须在 scope-guards.md 有定义与举例
  test('sensitive surfaces are defined with examples in scope-guards', () => {
    const scopeGuards = read(path.join(
      REPO_ROOT, 'skills', 'using-spec-first', 'references', 'scope-guards.md',
    ));
    const routingRedFlags = read(path.join(
      REPO_ROOT, 'skills', 'using-spec-first', 'references', 'routing-red-flags.md',
    ));

    // 定义段存在
    expect(scopeGuards).toContain('## Sensitive Surfaces');
    expect(scopeGuards).toContain('A **sensitive surface** is any area where');
    // 含分类与举例
    expect(scopeGuards).toContain('Architecture / contracts');
    expect(scopeGuards).toContain('Governance / routing');
    expect(scopeGuards).toContain('Runtime delivery');
    expect(scopeGuards).toMatch(/Not sensitive/);
    // 红旗引用定义而非重复
    expect(routingRedFlags).toContain('defined in `scope-guards.md`');
  });
});
